### ISSUE TITLE
Crashes with error "AttributeError: type object 'IOLoop' has no attribute 'initialized'"

### ISSUE THREAD

**Issue by jgomezdans** [mapbox/rio-glui#29]
Just cloned from github, installed with pip as per README (Python 3.6.4 environment) with no issues, and tried to launch the example command in the README:
```
$ rio glui https://oin-hotosm.s3.amazonaws.com/5ac626e091b5310010e0d482/0/5ac626e091b5310010e0d483.tif
Inspecting https://oin-hotosm.s3.amazonaws.com/5ac626e091b5310010e0d482/0/5ac626e091b5310010e0d483.tif at http://127.0.0.1:8080/index.html
Traceback (most recent call last):
  File "/opt/anaconda/envs/python3/bin/rio", line 11, in <module>
    sys.exit(main_group())
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda/envs/python3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/<USER>/python/rio-glui/rio_glui/scripts/cli.py", line 128, in glui
    app.start()
  File "/home/<USER>/python/rio-glui/rio_glui/server.py", line 125, in start
    is_running = IOLoop.initialized()
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```

I guess this is a Tornado issue. Installed version appears to be 5.0.1 if that's of any use?

**Comment by vincentsarago** [comment]
Hi @jgomezdans thanks for opening the issue. 

can you tell a bit more about your operating system ? 

Thanks

**Comment by jgomezdans** [comment]
Linux Ubuntu, 

    $ uname -a
    Linux 4.13.0-45-generic #50-Ubuntu SMP Wed May 30 08:23:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Python (3.6.4) installed from Anaconda 64-bit. Anything else you need to know?

**Comment by vincentsarago** [comment]
did a quick look around the Internet, this seems to be a `conda` error as mentioned here: 
- https://stackoverflow.com/questions/49141525/install-jupyter-notebook-on-miniconda
- https://github.com/jupyter/notebook/issues/3407

it seems you can either try: 
- `conda install -c conda-forge pyzmq` [ref](https://github.com/jupyter/notebook/issues/3595#issuecomment-389874572)
or
- `conda install tornado=4.5.3` [ref](https://stackoverflow.com/questions/49141525/install-jupyter-notebook-on-miniconda)

**Comment by vincentsarago** [comment]
@jgomezdans please feel free to close the issue if ☝️ solved the error

**Comment by jgomezdans** [comment]
Excellent! that worked!

**Comment by jgburd79** [comment]
So the installing tornado=4.5.3 works but the pip install flexx installs the latest 6.0.1 now. I don't think having to back install an older version is resolving the issue. It may make it work correctly but the issue will be propagated unless the installation is change to only install the correct version of tornado. The real issue would be why is the newest version causing the error and what needs to be change to fix it?

**Comment by kravigupta** [comment]
For Mac, and without conda, 

pip3 install tornado==4.5.3

worked fine.

**Comment by Erffa** [comment]
Thanks to you @kravigupta , this worked for me on linux Ubuntu 18.04.4 with a non-conda jupyter installation.

**Comment by kalimero76** [comment]
Thank very much it works fime :)

**Comment by kalimero76** [comment]
> For Mac, and without conda,
> 
> pip3 install tornado==4.5.3
> 
> worked fine.

It works fine, thanks !
